server:
  port: 8082
app:
  jwtSecret: asdfghjklpoiuytrewqzxcvbnmqazwsxedcrfvtgbyh
  jwtExpirationMs: 86400000
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    password: 
    url: jdbc:mysql://localhost:3306/venus
    username: root
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    password:  abctrjgaqqdxlqye

    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username:  ngocanhbui121093@gmail.com
